travis:
  secure:
    BINSTAR_TOKEN: rdWzuOvnk0D415vB6rnijgDI7qY8yVq+f6Tsn9uYFfrw56R/b4UgoAhsoeCbf17VHJnZ5VGbyB7ZPAUlDID83v9aaXqXW36AXnTJ1ia7neI41jqXuvKdt3stsfeowCV0vDpg5o6Nc3EPKgo6z5gYLxqXhRJL3rzMpFp4FwC5Qlb5ntU/mstqEJvCOkrH/T+bTuUsTt1w/CMkaR9RNvGDpkf7OD7vHcXe4lGgJdXwlqdbt5FKww8Qqy+KzufLztZWx5lF/rdk8LnmAFIhD3ZCiTrb/nallTTQAlkyX6kWB5jJmKUzQItER6mEJkkkaLgJmuMlJL5NEqJP2i+AHMhOgr9Pzr/wCjUMLnIn94hSxcrG0aTLwexJs/ZNBvhaQ0os1qZwjvn3MCJ2rcgfH/gjXN5tJShQHUe6jhtrDjarYGsMWdIYHGFbs5/Zm0lWe5keVPAfZCL8Iea4tLheVsTJpSEMltX6Zvm0jcRV4wwjo1Jebo4mGyIdWPtoD3Msp1rsq4tAjXqeZCg+WP25ysO/wcSN7ATe0kpWkgP756qq0eh3jmfqap4jRwvwqHp6O9mghcNC4CJ+mEMhp4CgkAw7gNRbbSLrkYcagb2jWIFigI4oVcog5mVOGGTjegN7QoBAWBTP3oSjps5kGJZRrc0hbZtani4KUY6cnVyfjbGVeRw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
